POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
authorization: bearer put_current_logged_in_user_jwt_here

{
  "author": "test author8",
  "url": "http://test8",
  "title": "test title8"
}

